name: Deploy Flask to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@54.237.97.48 << 'EOF'
          cd ~/flask-cicd || { echo "Failed to change directory"; exit 1; }
          rm -rf __pycache__/app.cpython-310.pyc
          git pull origin main || { echo "Failed to pull from Git"; exit 1; }
          source venv/bin/activate || { echo "Failed to activate virtual environment"; exit 1; }
          pip install -r requirements.txt || { echo "Failed to install requirements"; exit 1; }
          sudo systemctl daemon-reload || { echo "Failed to reload systemd"; exit 1; }
          sudo systemctl restart flask-app || { echo "Failed to restart Flask app"; exit 1; }
          sudo systemctl status flask-app || { echo "Flask app is not running"; exit 1; }
        EOF

